export const mockAvState = {
  connection: {
    connected: true,
    lastPacketMs: 12,
    droppedPackets: 0,
    latencyMs: 8,
  },
  transport: {
    playing: true,
    bpm: 128,
    bar: 12,
    beat: 3,
    sixteenth: 2,
    timeSignature: "4/4",
    scene: "DROP 1",
    progress: 0.62,
  },
  signal: {
    master: 0.72,
    peak: 0.91,
    rms: 0.64,
    bass: 0.82,
    mid: 0.45,
    high: 0.31,
    clipping: false,
  },
  tracks: [
    {
      name: "Kick",
      meter: 0.91,
      muted: false,
      soloed: false,
      armed: false,
      clip: "Drop Kick Loop",
    },
    {
      name: "Bass",
      meter: 0.76,
      muted: false,
      soloed: false,
      armed: false,
      clip: "Bass A",
    },
    {
      name: "Vocal",
      meter: 0.42,
      muted: false,
      soloed: false,
      armed: true,
      clip: "Vocal Chop",
    },
  ],
  macros: {
    intensity: 0.75,
    color: 0.2,
    motion: 0.5,
    particles: 0.9,
    glow: 0.4,
    strobe: 0.1,
    scene: 0.6,
    manual: 0,
  },
  debug: {
    fps: 60,
    websocket: "active",
    ableton: "connected",
  },
};
